import type { Metadata } from "next";
import "./globals.css";
import React, { ReactNode } from "react";
import { Provider } from "./Providers";
import Navbar from "@/Components/NavBar";

export const metadata: Metadata = {
  title: "T-Sender",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Navbar/>
          {props.children}
          </Provider>
      </body>
    </html>
  );
}
